version: "3"

services: 
  foxglove:
    image: ghcr.io/foxglove/studio:latest
    ports:
      - target: 8765
        published: 8765
        protocol: tcp
        mode: host
    network_mode: "host"
    volumes:
      - ../../.foxglove/xarm_joint_positions.json:/foxglove/default-layout.json
  
  foxglove_bridge:
    image: ghcr.io/peterdavidfagan/foxglove_bridge:rolling
    network_mode: "host"

  moveit:
    image: ghcr.io/peterdavidfagan/lite6_motion_planning:rolling
    build: 
      context: ../../
      dockerfile: .docker/motion_planning/Dockerfile.motion_planning
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${DOCKER_XAUTH}
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
    network_mode: "host"
    devices:
      - "/dev:/dev"
    privileged: true
    command: ros2 launch lite6_motion_planning_demos motion_planning_prerequisites.launch.py

  notebook_server:
    image: ghcr.io/peterdavidfagan/lite6_motion_planning:rolling
    build: 
      context: ../../
      dockerfile: .docker/motion_planning/Dockerfile.motion_planning
    network_mode: "host"
    command: python3 -m notebook --allow-root --NotebookApp.token='' # TODO: move to local config

